### ISSUE TITLE
PVS -> PVS-Studio

### ISSUE THREAD

**Issue by AndreyKarpov** [pffan91/Insert-PVS-Comment#1]
Hello Vladyslav,

I was surprised to see a new tool Insert-PVS-Comment on marketplace.visualstudio. If it will always only add comments but not delete them, then I'm glad this tool exists. I could even write a post about it on Twitter if you like.

The only thing I'd like to ask of you is to replace PVS with PVS-Studio everywhere, including the logo. You see, we'd like to maintain uniformity everywhere. Besides, your tool will have more search hits that way.

What about carrying out all further correspondence by email? My email address is karpov [@] viva64.com

----
Best regards,
Andrey Karpov, Microsoft MVP,
Ph.D. in Mathematics, CTO
"Program Verification Systems" Co Ltd.
URL: www.viva64.com

**Comment by pffan91** [comment]
Hello, @AndreyKarpov ! Thank you for this opportunity. I changed all texts to PVS-Studio and updated icon. New version is in the market. 

P.S. Hope that you received my email.
